---
name: Bug report
about: Create a report to help us improve
title: Bug report
labels: bug-report
assignees: petar

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
A clear and concise description of what you expected to happen.

**Attach the logs**
Attach the logs from reproducing the bug using the verbose flag `-v`